  name: Node.js CI

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    build-and-test:
      runs-on: ubuntu-latest

      services:
        mysql:
          image: mysql:8.0
          env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sms_new
          ports:
            - 3306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '22'
            cache: 'npm'

        - name: Install dependencies
          run: npm install

        - name: Prisma Generate
          run: npx prisma generate

        - name: Check Formatting
          run: npm run format:check

        - name: Run Lint
          run: npm run lint

        - name: Build TypeScript
          run: npm run build
        
        
        - name: Wait for MySQL to be ready
          run: sleep 20

        - name: Prisma Generate & Migrate
          env:
            # Secret ကို မသုံးဘဲ Direct Localhost URL ကို ရေးပေးလိုက်ပါ
            DATABASE_URL: "mysql://root:root@127.0.0.1:3306/sms_new"
          run: |
            npx prisma generate
            npx prisma db push


        - name: Run Tests
          env:
            # ဒီနေရာမှာလည်း Localhost IP တွေကိုပဲ သုံးရပါမယ်
            DATABASE_URL: "mysql://root:root@127.0.0.1:3306/sms_new"
            DATABASE_HOST: "127.0.0.1"
            DATABASE_USER: "root"
            DATABASE_PASSWORD: "root"
            DATABASE_NAME: "sms_new"
            DATABASE_PORT: "3306"
          run: NODE_OPTIONS=--experimental-vm-modules npm test
