name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ပထမ Job: စစ်ဆေးတဲ့အပိုင်း
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sms_new
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Prisma Generate
        run: npx prisma generate
        
      - name: Check Formatting
        run: npm run format:check

      - name: Run Lint
        run: npm run lint

      - name: Build TypeScript
        run: npm run build

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Prisma Db Push
        env:
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/sms_new"
        run: npx prisma db push

      - name: Run Tests
        env:
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/sms_new"
          NODE_ENV: test
        run: NODE_OPTIONS=--experimental-vm-modules npm test

  # ဒုတိယ Job: Deploy လုပ်တဲ့အပိုင်း (Indentation သတိထားပါ)
  deploy:
    needs: build-and-test 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_DEST }}
            git pull origin main
            npm install --legacy-peer-deps
            npx prisma generate
            npm run build
            pm2 restart my-node-ci || pm2 start dist/app.js --name "my-node-ci-cd test"

      - name: Send Success Notification
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Deployment Success!
            Project: ${{ github.repository }}
            Author: ${{ github.actor }}
            🚀 Server is now updated!

      - name: Send Failure Notification
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Deployment Failed!
            Project: ${{ github.repository }}
            Check logs here: https://github.com/${{ github.repository }}/actions